# Generated by Django 4.1.5 on 2023-01-17 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canguru_app', '0005_alter_user_career_direction_alter_user_date_of_birth_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='career_direction',
        ),
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=64, null=True, verbose_name='Пароль'),
        ),
    ]
