# Generated by Django 4.1.5 on 2023-01-22 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canguru_app', '0011_area_grade_remove_user_is_active_module_user_grade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='name',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
    ]
