# Generated by Django 4.1.5 on 2023-01-22 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canguru_app', '0013_alter_module_area'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
