# Generated by Django 4.1.5 on 2023-01-22 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canguru_app', '0015_module_grade'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modules_junior', models.IntegerField()),
                ('modules_junior_plus', models.IntegerField()),
                ('modules_middle', models.IntegerField()),
                ('modules_middle_plus', models.IntegerField()),
                ('modules_senior', models.IntegerField()),
            ],
        ),
    ]
