# Generated by Django 4.1.5 on 2023-01-22 17:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('canguru_app', '0016_tracking'),
    ]

    operations = [
        migrations.AddField(
            model_name='tracking',
            name='user_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
