# Generated by Django 4.1.5 on 2023-01-22 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('canguru_app', '0017_tracking_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tracking',
            old_name='user_id',
            new_name='user',
        ),
    ]
